### ISSUE TITLE
PIP Installs Older Version?

### ISSUE THREAD

**Issue by jevchance** [time4tea/gopro-dashboard-overlay#140]
Hi,
I'm having trouble getting the newest version of the software for Mac OS. When I try to install and run the software I get this error:

MEEP@Shockwave Scripts % python -m venv venv
zsh: command not found: python
MEEP@Shockwave Scripts % python3 -m venv venv
MEEP@Shockwave Scripts % venv/bin/pip install gopro-overlay
Collecting gopro-overlay
  Using cached gopro_overlay-0.79.0-py3-none-any.whl
Collecting pint==0.20.1
  Using cached Pint-0.20.1-py3-none-any.whl (269 kB)
Collecting progressbar2==4.2.0
  Using cached progressbar2-4.2.0-py2.py3-none-any.whl (27 kB)
Collecting requests==2.28.2
  Using cached requests-2.28.2-py3-none-any.whl (62 kB)
Collecting fitdecode==0.10.0
  Using cached fitdecode-0.10.0-py3-none-any.whl (90 kB)
Collecting geotiler==0.14.7
  Using cached geotiler-0.14.7-py3-none-any.whl
Collecting geographiclib==1.52
  Using cached geographiclib-1.52-py3-none-any.whl (38 kB)
Collecting pillow==9.4.0
  Using cached Pillow-9.4.0-2-cp39-cp39-macosx_10_10_x86_64.whl (3.3 MB)
Collecting gpxpy==1.5.0
  Using cached gpxpy-1.5.0-py3-none-any.whl
Collecting aiohttp>=2.3.5
  Using cached aiohttp-3.8.4-cp39-cp39-macosx_10_9_x86_64.whl (360 kB)
Collecting cytoolz>=0.8.2
  Using cached cytoolz-0.12.1-cp39-cp39-macosx_10_9_x86_64.whl (410 kB)
Requirement already satisfied: setuptools in ./venv/lib/python3.9/site-packages (from geotiler==0.14.7->gopro-overlay) (59.0.1)
Collecting python-utils>=3.0.0
  Using cached python_utils-3.7.0-py2.py3-none-any.whl (26 kB)
Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.1.0-cp39-cp39-macosx_10_9_x86_64.whl (124 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.16-py2.py3-none-any.whl (143 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2023.5.7-py3-none-any.whl (156 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting async-timeout<5.0,>=4.0.0a3
  Using cached async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Collecting aiosignal>=1.1.2
  Using cached aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Collecting frozenlist>=1.1.1
  Using cached frozenlist-1.3.3-cp39-cp39-macosx_10_9_x86_64.whl (36 kB)
Collecting yarl<2.0,>=1.0
  Using cached yarl-1.9.2-cp39-cp39-macosx_10_9_x86_64.whl (65 kB)
Collecting attrs>=17.3.0
  Using cached attrs-23.1.0-py3-none-any.whl (61 kB)
Collecting multidict<7.0,>=4.5
  Using cached multidict-6.0.4-cp39-cp39-macosx_10_9_x86_64.whl (29 kB)
Collecting toolz>=0.8.0
  Using cached toolz-0.12.0-py3-none-any.whl (55 kB)
Collecting typing-extensions>3.10.0.2
  Using cached typing_extensions-4.7.1-py3-none-any.whl (33 kB)
Installing collected packages: multidict, idna, frozenlist, yarl, typing-extensions, toolz, charset-normalizer, attrs, async-timeout, aiosignal, urllib3, python-utils, pillow, cytoolz, certifi, aiohttp, requests, progressbar2, pint, gpxpy, geotiler, geographiclib, fitdecode, gopro-overlay
Successfully installed aiohttp-3.8.4 aiosignal-1.3.1 async-timeout-4.0.2 attrs-23.1.0 certifi-2023.5.7 charset-normalizer-3.1.0 cytoolz-0.12.1 fitdecode-0.10.0 frozenlist-1.3.3 geographiclib-1.52 geotiler-0.14.7 gopro-overlay-0.79.0 gpxpy-1.5.0 idna-3.4 multidict-6.0.4 pillow-9.4.0 pint-0.20.1 progressbar2-4.2.0 python-utils-3.7.0 requests-2.28.2 toolz-0.12.0 typing-extensions-4.7.1 urllib3-1.26.16 yarl-1.9.2
WARNING: You are using pip version 21.3.1; however, version 23.1.2 is available.
You should consider upgrading via the '/Users/MEEP/Scripts/venv/bin/python3.9 -m pip install --upgrade pip' command.
MEEP@Shockwave Scripts % venv/bin/gopro-dashboard.py /Users/MEEP/Movies/Personal/GVSU\ AutoX\ 7-2-2023/Source\ Footage/GoPro1/GX010158.MP4 /Users/MEEP/Movies/Personal/GVSU\ AutoX\ 7-2-2023/Source\ Footage/GoPro1/GX010158-dash.MP4
Starting gopro-dashboard version 0.79.0
    Timer(GPMD - Called: 1, Total: 0.14266, Avg: 0.14266, Rate: 7.01)
    Timer(extract GPS - Called: 1, Total: 0.52282, Avg: 0.52282, Rate: 1.91)
Request for data at time Timeunit ms=-5.841, before start of metadata, returning first item
    Timer(extract ACCL - Called: 1, Total: 1.81020, Avg: 1.81020, Rate: 0.55)
Request for data at time Timeunit ms=-5.841, before start of metadata, returning first item
    Timer(extract GRAV - Called: 1, Total: 0.72323, Avg: 0.72323, Rate: 1.38)
Request for data at time Timeunit ms=-5.841, before start of metadata, returning first item
    Timer(extract CORI - Called: 1, Total: 1.12059, Avg: 1.12059, Rate: 0.89)
Timer(parsing - Called: 1, Total: 4.31988, Avg: 4.31988, Rate: 0.23)
Timer(loading timeseries - Called: 1, Total: 4.71451, Avg: 4.71451, Rate: 0.21)
Timer(program - Called: 1, Total: 4.71456, Avg: 4.71456, Rate: 0.21)
Traceback (most recent call last):
  File "/Users/MEEP/Scripts/venv/bin/gopro-dashboard.py", line 177, in <module>
    if counter.total() > 0:
AttributeError: 'ReasonCounter' object has no attribute 'total'
MEEP@Shockwave Scripts % python3 --version
Python 3.9.9

**Comment by jevchance** [comment]
Note: when I try to install with PIP using the --no-cache-dir option, I get the same result.

**Comment by time4tea** [comment]
Hi.

Thanks for trying the software and taking the time to report an issue.

I've not seen this. Are you deleting the existing venv directory before reinstalling? Please try that, and see if it makes a difference.

One thing I did note is that you are using an unsupported version of python, 3.9.9. This software will not work with that - it needs minimum 3.10.

The requirements are listed at: https://github.com/time4tea/gopro-dashboard-overlay#requirements

James

**Comment by time4tea** [comment]
Did you manage to make any progress?
